<?php
/**
 * Created by PhpStorm.
 * User: filanor
 * Date: 2019-04-04
 * Time: 21:08
 */

error_reporting(E_ALL & ~E_NOTICE);

abstract class Product
{
    public $item;
    public $price;
    public $weight;
    private static $count = 0;

    public function __construct($item, $price, $weight)
    {
        $this->item = gettype($item) == 'string' ? $item : 'неверный формат';
        $this->price = (gettype($price) == 'integer'|| gettype($price) == 'double') ? $price : 0;
        $this->weight = (gettype($weight) == 'integer' || gettype($weight) == 'double') ? $weight : 0;
    }

    public function showImage($image, $w)
    {
        echo "<div style='width: 300px;margin: 50px auto;'>
              <div style = 'width:{$w}px; height:{$w}px; background-image: url({$image});background-size: contain'></div>
              </div>
        ";
    }


    public function printProduct()
    {
        echo "<div style='width: 300px;margin: 50px auto; border: 1px solid #e6e6e6;'>
                <div style = 'border-bottom: 1px solid #e6e6e6; padding: 10px'>
                    <span style = 'width:50%;display:block;float:left'>Название</span>
                    <span style = 'width:50%;display:block;float:right'>{$this->item}</span>
                </div>
                <div style = 'border-bottom: 1px solid #e6e6e6; padding: 10px'>
                    <span style = 'width:50%;display:block;float:left'>Вес</span>
                    <span style = 'width:50%;display:block;float:right'>{$this->weight}</span>
                </div>
                <div style = 'border-bottom: 1px solid #e6e6e6; padding: 10px'>
                    <span style = 'width:50%;display:block;float:left'>Цена</span>
                    <span style = 'width:50%;display:block;float:right'>{$this->price}</span>
                </div>
            </div>";
    }

    public function printProductNDS()
    {
        $ndsFree = round($this->price - $this->price * (20/120),2);
        echo "<div style='width: 300px;margin: 50px auto; border: 1px solid #e6e6e6;'>
                <div style = 'border-bottom: 1px solid #e6e6e6; padding: 10px'>
                    <span style = 'width:50%;display:block;float:left'>Название</span>
                    <span style = 'width:50%;display:block;float:right'>{$this->item}</span>
                </div>
                <div style = 'border-bottom: 1px solid #e6e6e6; padding: 10px'>
                    <span style = 'width:50%;display:block;float:left'>Вес</span>
                    <span style = 'width:50%;display:block;float:right'>{$this->weight}</span>
                </div>
                <div style = 'border-bottom: 1px solid #e6e6e6; padding: 10px'>
                    <span style = 'width:50%;display:block;float:left'>Цена c НДС</span>
                    <span style = 'width:50%;display:block;float:right'>{$this->price}</span>
                </div>
                <div style = 'border-bottom: 1px solid #e6e6e6; padding: 10px'>
                    <span style = 'width:50%;display:block;float:left'>Цена без НДС</span>
                    <span style = 'width:50%;display:block;float:right'>{$ndsFree}</span>
                </div>
            </div>";
    }
}


class Chocolate extends Product
{
    public $colory;

    public function __construct($item, $price, $weight, int $colory)
    {
        parent::__construct($item, $price, $weight);
        $this->colory = $colory;
    }

    public function showImage()
    {
        parent::showImage('сhoco.jpeg', 200); // TODO: Change the autogenerated stub
    }

}

class Candy extends Product
{
    public function __construct($item, $price, $weight)
    {
        parent::__construct($item, $price, $weight);
    }

    public function showImage()
    {
        parent::showImage('candy.jpeg', 100); // TODO: Change the autogenerated stub
    }

}


$candy = new Candy('Аленка', 100, 0.1);
$candy->showImage();


$choco = new Chocolate('Аленка', 100, 0.1, 1500);
$choco->showImage();

